packages:
  - '.'

allowBuilds:
  '@vue-office/docx': set this to true or false
  '@vue-office/excel': set this to true or false
  '@vue-office/pdf': set this to true or false
  '@vue-office/pptx': set this to true or false
  esbuild: true
  vue-demi: true
